# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyj_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cyj_user',
            name='introduction',
        ),
        migrations.AddField(
            model_name='cyj_user',
            name='uemail',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='邮箱'),
            preserve_default=False,
        ),
    ]
