# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyj_user', '0002_auto_20180802_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyj_user',
            name='upassword',
            field=models.CharField(max_length=100, verbose_name='密码'),
        ),
    ]
