# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 11:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyj_user', '0003_auto_20180802_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyj_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
