# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyj_furniture', '0003_auto_20180801_0827'),
        ('cyj_user', '0005_comment'),
    ]


