# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CYJ_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adname', models.CharField(max_length=50, verbose_name='管理员')),
                ('adpassword', models.IntegerField(verbose_name='密码')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
