# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyj_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100, verbose_name='家具种类')),
                ('content', models.CharField(max_length=300, verbose_name='基本信息')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('img', models.ImageField(null=True, upload_to='images/', verbose_name='图片')),
                ('sales', models.IntegerField(null=True, verbose_name='销量')),
                ('url', models.CharField(max_length=200, null=True, verbose_name='链接')),
                ('click', models.IntegerField(default=0, verbose_name='点击量')),
                ('isfavorite', models.BooleanField(default=0, verbose_name='是否收藏')),
                ('mm_user', models.ManyToManyField(to='cyj_user.CYJ_user')),
            ],
            options={
                'db_table': 'furniture',
            },
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fstyle', models.CharField(max_length=50, verbose_name='样式')),
            ],
        ),
        migrations.AddField(
            model_name='furniture',
            name='typeinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyj_furniture.TypeInfo'),
        ),
    ]
