# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyj_furniture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='url',
            field=models.CharField(max_length=800, null=True, verbose_name='链接'),
        ),
    ]
