# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyj_furniture', '0004_cart_deliveryaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyj_user.CYJ_user'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyj_user.CYJ_user'),
        ),
    ]
